### ISSUE TITLE
LocalizationResourceManager question

### ISSUE THREAD

**Issue by santo998** [SirJohnK/LocalizationResourceManager.Maui#20]
Hello, I hope you are doing good!

My question is:
Why are you using Jon Skeet Singleton pattern on LocalizationResourceManager class?
This one: https://www.jonskeet.uk/csharp/singleton.html

Is it even needed? Won't it be registered as singleton on MAUI dependency injection anyways?

**Comment by SirJohnK** [comment]
2 reasons.
- This library is a replacement library for the ```LocalizationResourceManager``` in [Xamarin Community Toolkit](https://github.com/xamarin/XamarinCommunityToolkit/blob/main/src/CommunityToolkit/Xamarin.CommunityToolkit/Helpers/LocalizationResourceManager.shared.cs) and I wanted to change as little as possible to upgrade from Xamarin to Maui.
- For XAML, the ```IMarkupExtension``` is used to access resources and that is not resolved by the DI container. So injecting the ```ILocalizationResourceManage``` is not possible. Resolving it internally is possible, but then you need a reference to the ```ServiceProvider```.

```ILocalizationResourceManage``` will be registered with DI and is the prefered/recommended way of using for classes resolved by the DI Container. e.g. Views / ViewModels

Note: Please create a ```Discussion``` instead of an ```Issue``` for this kind of topics in the future, thanks!
